Order in pdf file
edikkiz/clockwise_clockware_full pull request #23
Opened 2021-11-26 13:25 UTC by edikkiz

2021-11-26 14:14 UTC, tup1tsa requested changes

2021-11-26 14:14 UTC, tup1tsa commented on client/src/components/Master/masterWorkList/masterWorkList.tsx
> +  const downloadPDF = (order: AllOrder) => {
Переделать. ПДФ должен генерироваться сервером по orderID + user-token

2021-11-26 14:14 UTC, tup1tsa commented on src/controller/order.controller.ts
> +                pdf.create(string).toBuffer(function (err, buffer) {
переписать на промисы

2021-11-26 14:14 UTC, tup1tsa commented on src/controller/order.controller.ts
> +                res.status(201).json(upOrder)
Статус отправится раньше, чем придет ответ sendMail

2021-11-26 14:14 UTC, tup1tsa commented on src/controller/order.controller.ts
> +            select: {
Поубирать все cелекты и заменить на include

2021-11-26 14:14 UTC, tup1tsa commented on src/controller/order.controller.ts
> +            if (status === 'Completed' && user?.email && order) {
Как у юзера может не быть имейла?

2021-11-26 14:14 UTC, tup1tsa commented on src/controller/order.controller.ts
> +            pdf.create(string).toBuffer(function (err, buffer) {
Почему в двух местах пдф отправляется? и вообще письмо почему в двух местах отправляется? DRY нарушается

2021-11-26 14:14 UTC, tup1tsa commented on src/services/sendMail.ts
> +        attachments: [
attachments всегда отправляется, даже если pdf === undefined?

2021-11-26 14:14 UTC, tup1tsa commented on src/pdf/pdf.ts
> +  <table align="center">
Нарушения принципа DRY. Генерация на фронте может начать отличаться со временем

2021-11-29 13:37 UTC, tup1tsa requested changes

2021-11-29 13:37 UTC, tup1tsa commented on client/package.json
> +    "jspdf": "^2.4.0",
Зачем это тут?

2021-11-29 13:37 UTC, tup1tsa commented on client/src/components/Admin/controllerOrder/orderCharts/charts/tableMaster/TableMaster.tsx
> +              }$`}</th>
доллары всегда пишутся сначала, а не в конце

2021-11-29 13:37 UTC, tup1tsa commented on client/src/components/Master/masterWorkList/masterWorkList.tsx
> +    saveAs(blob, 'mypdf.pdf')
думаешь будет удобно работать, если имена будут mypdf.pdf для всех заказов?

2021-11-29 13:37 UTC, tup1tsa commented on client/src/components/User/userList/UserList.tsx
> +              {!order.images.length ? (
Какое отношение этот файл имеет к пдф?

2021-11-29 13:37 UTC, tup1tsa commented on src/controller/order.controller.ts
> +        'pdf.pdf',
нужно лучше название. pdf.pdf не канает

2021-11-29 13:37 UTC, tup1tsa commented on src/controller/order.controller.ts
> +                pdf.create(string).toBuffer(async (err, buffer) => {
почему не через промисы?

2021-11-29 13:37 UTC, tup1tsa commented on src/controller/order.controller.ts
> +                    SendEmailIfStatusComplited(
почему с большой буквы функция? почему с опечаткой?

2021-11-29 13:37 UTC, tup1tsa commented on src/controller/order.controller.ts
> +                        buffer,
а какое название у файла будет?

2021-11-29 13:37 UTC, tup1tsa commented on src/controller/order.controller.ts
> +                    SendEmailIfStatusComplited(email, feedbackToken, buffer)
где await

2021-11-29 13:37 UTC, tup1tsa commented on src/controller/order.controller.ts
> +                pdf.create(string).toBuffer(async (err, buffer) => {
Где промисы? код так не пишут уже давно

2021-11-29 13:37 UTC, tup1tsa commented on src/controller/order.controller.ts
> +            pdf.create(string).toFile(`${__dirname}/../mypdf.pdf`, err => {
где промисы?

2021-11-29 13:37 UTC, tup1tsa commented on src/controller/order.controller.ts
> +            pdf.create(string).toFile(`${__dirname}/../mypdf.pdf`, err => {
Где обработка ошибки?

2021-11-29 13:37 UTC, tup1tsa commented on src/controller/order.controller.ts
> +                res.download(`${__dirname}/../mypdf.pdf`)
Нарушение DRY

2021-11-29 13:37 UTC, tup1tsa commented on src/services/sendMail.ts
> +        await transporter.sendMail({
Нарушение принципа DRY

2021-11-29 13:37 UTC, tup1tsa commented on src/services/sendMail.ts
> +    console.log('Server is ready to take our messages')
Сервер может начать получать запросы до того, как запустился имейл сервис.

2021-11-30 14:16 UTC, tup1tsa requested changes

2021-11-30 14:16 UTC, tup1tsa commented on client/src/components/Master/masterWorkList/masterWorkList.tsx
> +    const { data } = await axios.get('/master/orderPdf', {
Где error-handling? Если вылетит ошибка, isLoading так и будет true

2021-11-30 14:16 UTC, tup1tsa commented on client/src/components/Master/masterWorkList/masterWorkList.tsx
> +        'Content-Disposition': 'attachment; john-resume.pdf',
john-resume?

2021-11-30 14:16 UTC, tup1tsa commented on client/package-lock.json
> +    "@types/raf": {
Здесь тоже не должно быть нигде изменений

2021-11-30 14:16 UTC, tup1tsa commented on src/controller/order.controller.ts
> +// import child_process from 'child_process'
убрать комменты

2021-11-30 14:16 UTC, tup1tsa commented on src/controller/order.controller.ts
> +const sendEmailIfStatusCompleted = async (
Зачем эта конструкция? Абстракция ради абстракции

2021-11-30 14:16 UTC, tup1tsa commented on src/controller/order.controller.ts
> +                const createPDFBuffer = (
Второй раз указана одна и та же функция (один в один)

2021-11-30 14:16 UTC, tup1tsa commented on src/controller/order.controller.ts
> +            const createPDFFile = (HTMLString: string) => {
Третий раз одна и та же функция

2021-11-30 14:16 UTC, tup1tsa commented on src/routes/masterRole.router.ts
> +router.get('/orderPdf', orderController.sendCheckPdfFile)
Почему этот путь не в том же месте, где и остальные эндпоинты для заказа?
`order/:id`, `/order/:id/pdf`, etc

2021-11-30 14:16 UTC, tup1tsa commented on src/services/sendMail.ts
> +        const file = [
зачем эта промежуточная переменная?

2021-11-30 14:18 UTC, tup1tsa requested changes

2021-11-30 14:18 UTC, tup1tsa commented on src/services/sendMail.ts
> +    console.log('Server is ready to take our messages')
И? Нужно пофиксить, только в отдельном пулл реквесте

2021-11-30 15:57 UTC, edikkiz commented on src/routes/masterRole.router.ts
> +router.get('/orderPdf', orderController.sendCheckPdfFile)
скачивание пдф файла происходит с рабочего места мастера, по этому роут тут, там же проверяется токен мастера.

2021-11-30 15:57 UTC, edikkiz commented on src/services/sendMail.ts
> +        const file = [
что бы отправлять письмо с файлом или без него.

2021-11-30 15:58 UTC, edikkiz commented on src/controller/order.controller.ts
> +                const createPDFBuffer = (
функция принимает аргументом конкретный заказ и возвращает html разметку для этого заказа,

2021-12-01 10:30 UTC, tup1tsa requested changes

2021-12-01 10:30 UTC, tup1tsa commented on client/package.json
> +    "jspdf": "^2.4.0",
Зачем это тут?

2021-12-01 10:30 UTC, tup1tsa commented on client/src/components/Admin/controllerOrder/orderCharts/charts/tableMaster/TableMaster.tsx
> +              }$`}</th>
доллары всегда пишутся сначала, а не в конце

2021-12-01 10:30 UTC, tup1tsa commented on client/src/components/Master/masterWorkList/masterWorkList.tsx
> +    const { data } = await axios.get('/master/orderPdf', {
Где error-handling? Если вылетит ошибка, isLoading так и будет true

2021-12-01 10:30 UTC, tup1tsa commented on client/src/components/Master/masterWorkList/masterWorkList.tsx
> +                    onClick={() => downloadPDF(order, order.id)}
Зачем передавтаь order.id, если там уже есть order объект?

2021-12-01 10:30 UTC, tup1tsa commented on src/controller/order.controller.ts
> +        `${fileName}.pdf`,
если fileName не передавать, будет undefined.pdf

2021-12-01 10:30 UTC, tup1tsa commented on src/controller/order.controller.ts
> +                }
сreatePDFBuffer повторяется

2021-12-01 10:30 UTC, tup1tsa commented on src/controller/order.controller.ts
> +                }
сreatePDFBuffer повторяется

2021-12-01 10:30 UTC, tup1tsa commented on src/controller/order.controller.ts
> +            if (feedbackToken) {
Каков будет ответ на фронт, если по какой-то причине feedbackToken будет отсутствовать?

2021-12-01 10:30 UTC, tup1tsa commented on src/controller/order.controller.ts
> +                })
Почему update происходит после того, как отправилось письмо? А если упадёт?

2021-12-01 10:30 UTC, tup1tsa commented on src/controller/order.controller.ts
> +        if (order) {
Каков будет ответ, если ордера нет?

2021-12-01 11:33 UTC, tup1tsa requested changes

2021-12-01 11:33 UTC, tup1tsa commented on client/src/components/Master/masterWorkList/masterWorkList.tsx
> +      .then(res => {
не используй then + catch вместе с await
используй try { await // code} catch (e) {// error handling}

2021-12-01 11:33 UTC, tup1tsa commented on src/controller/order.controller.ts
> +    dataForPdf?: {
Разве есть возможность не отправлять пдф? Почему здесь `?`

2021-12-01 11:33 UTC, tup1tsa commented on src/controller/order.controller.ts
> +    await sendMail(
бесполезный await

какая разница между следующими функциями (и какой вид стоит применять в твоём случае)?
Попробуй описать их типы (чтобы я понял, что ты понимаешь разницу)
```
type SendMail = () => Promise<string>
const sendMail: SendMail = async () => {
  return new Promise((resolve) => resolve('sdf'))
}

// first function
type WithUselessAwait = ??
const  withUselessAwait: WithUselessAwait =async () => {
  await sendMail()
}

// second function
type WithReturn = ??
const  withReturn : WithReturn = async () => {
  return sendMail()
}

// third function
type WithoutReturn = ??
const  withouReturn : WithouReturn = async () => {
  sendMail()
}

// fourth function
type WithoutAsync  = ??
const  withoutAsync : WithoutAsync = () => {
  sendMail()
}

// fifth function
type WithoutAsyncWithReturn  = ??
const  withoutAsyncWithReturn  : WithoutAsyncWithReturn  = () => {
  return sendMail()
}

```

2021-12-01 11:33 UTC, tup1tsa commented on src/controller/order.controller.ts
> +            if (feedbackToken) {
Не учись плодить лишнюю вложенность
```
if (!feedbackToken) {
  sendError()
  return // или даже return sendError()
}
// дальше уже будет без вложенности
```

2021-12-01 11:33 UTC, tup1tsa commented on src/controller/order.controller.ts
> +        } else {
бесполезный else и вложенность. Ну,при условии, что с предыдущего блока будет return

2021-12-01 11:43 UTC, edikkiz commented on src/controller/order.controller.ts
> +    dataForPdf?: {
да есть если при создании заказа не было ещё юзера, то отправляется на почту сообщение с паролем от его личного кабинета.

2021-12-01 12:44 UTC, edikkiz commented on src/controller/order.controller.ts
> +            if (feedbackToken) {
у order feedbackToken может быть null, как тут без вложенности?

2021-12-01 12:54 UTC, edikkiz commented on src/controller/order.controller.ts
> +    await sendMail(
type WithUselessAwait = Promise
const  withUselessAwait: WithUselessAwait =async ()  => {
  await sendMail()
}
type WithReturn = вернет Promise<string>
const  withReturn : WithReturn = async () => {
  return sendMail()
}
type WithoutReturn = Promise
const  withouReturn : WithouReturn = async () => {
  sendMail()
}
type WithoutAsync  = ничего не вернет
const  withoutAsync : WithoutAsync = () => {
  sendMail()
}
type WithoutAsyncWithReturn  = Promise<string>
const  withoutAsyncWithReturn  : WithoutAsyncWithReturn  = () => {
  return sendMail()
}

2021-12-01 13:05 UTC, tup1tsa commented on src/controller/order.controller.ts
> +    await sendMail(
невалидный ts code

2021-12-01 13:10 UTC, merged